///////////////////////////////////////////////////////////
//  Facility.cs
//  Implementation of the Class Facility
//  Generated by Enterprise Architect
//  Created on:      29-Dec-2020 11:08:45 AM
//  Original author: 0wner
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Business;
using System.Data;
using UTMALIS_ROLLNEY.DLL.UTMALISDataSetTableAdapters;

namespace Business {
	public class Facility {

		private string Facilityname;
		private float Facilityprice;
		private string Facilitytype;
		private int FacilityID;
		public Facility(){

		}

		~Facility(){

		}

		/// 
		/// <param name="Facilityname"></param>
		/// <param name="Reservationdate"></param>
		/// <param name="Package"></param>
		/// <param name="Facilitytype"></param>

		public DataTable GetData()
		{
			FacilityTableAdapter fta = new FacilityTableAdapter();
			DataTable dt = new DataTable();
			dt = fta.GetData();
			return dt;
		}



	}//end Facility

}//end namespace Business