///////////////////////////////////////////////////////////
//  Reservation.cs
//  Implementation of the Class Reservation
//  Generated by Enterprise Architect
//  Created on:      29-Dec-2020 11:08:45 AM
//  Original author: 0wner
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Business;
using System.Data;
using UTMALIS_ROLLNEY.DLL.UTMALISDataSetTableAdapters;

namespace Business
{
	public class Reservation
	{

		private string Package;
		private DateTime ReservationDate;
		private Business.Facility m_Facility;
		private Business.Payment m_Payment;

		public Reservation()
		{

		}

		~Reservation()
		{

		}

		/// 
		/// <param name="Package"></param>
		/// <param name="ReservationDate"></param>
		/// <param name="ReservationID"></param>
		public DataTable GetData()
		{
			ReservationTableAdapter rta = new ReservationTableAdapter();
			DataTable rt = new DataTable();
			rt = rta.GetData();
			return rt;
		}

		public void addReservation(string Package, DateTime ReservationDate, string ReservationID, int FacilityID)
		{
			ReservationTableAdapter rta = new ReservationTableAdapter();
			rta.addReservation(Package, (ReservationDate).ToString(), int.Parse(ReservationID), FacilityID);
		}

		public Facility FacilityID
		{
			get
			{
				return m_Facility;
			}
			set
			{
				m_Facility = value;
			}
		}

		public Payment PaymentID
		{
			get
			{
				return m_Payment;
			}
			set
			{
				m_Payment = value;
			}
		}

		public void save()
		{

		}


	}//end Reservation

}//end namespace Business

public abstract class Package { }

public abstract class Equipment { }

public abstract class Facilities
{
	public abstract Package CreatePackage();
	public abstract Equipment CreateEquipment();
	public abstract Equipment CreateEquipment2();
}

public class A : Package { }

class Wisel : Equipment { }

class ScoreBoard : Equipment { }

public class SportFacilities : Facilities
{
    public override Package CreatePackage()
    {
		return new A();
    }
	
    public override Equipment CreateEquipment()
    {
        return new Wisel();
    }

	public override Equipment CreateEquipment2()
	{
		return new ScoreBoard();
	}

}

public class B : Package { }

class Chair : Equipment { }

class Table : Equipment { }

public class HallFacilities : Facilities
{
	public override Package CreatePackage()
	{
		return new B();
	}

	public override Equipment CreateEquipment()
	{
		return new Chair();
	}

	public override Equipment CreateEquipment2()
	{
		return new Table();
	}
}

public class C : Package { }

class Projector : Equipment { }

class Lab : Equipment { }

public class ComputerFacilities : Facilities
{
	public override Package CreatePackage()
	{
		return new C();
	}

	public override Equipment CreateEquipment()
	{
		return new Projector();
	}

	public override Equipment CreateEquipment2()
	{
		return new Lab();
	}
}

public class D : Package { }

class Racket : Equipment { }

class Net : Equipment { }

public class CourtFacilities : Facilities
{
	public override Package CreatePackage()
	{
		return new D();
	}

	public override Equipment CreateEquipment()
	{
		return new Racket();
	}

	public override Equipment CreateEquipment2()
	{
		return new Net();
	}
}