///////////////////////////////////////////////////////////
//  UTM Alumni.cs
//  Implementation of the Class UTM Alumni
//  Generated by Enterprise Architect
//  Created on:      29-Dec-2020 11:08:45 AM
//  Original author: 0wner
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Business;
namespace Business {
	public class UTMAlumni {

		private string Alumnipoint;
		private string Email;
		private string Name;
		private string Password;
		private int Phone;
		private Business.Activity m_Activity;
		private Business.Donation m_Donation;
		private Business.Reservation m_Reservation;

		public UTMAlumni(){

		}

		~UTMAlumni(){

		}

		public Activity Activity{
			get{
				return m_Activity;
			}
			set{
				m_Activity = value;
			}
		}

		public Donation Donation{
			get{
				return m_Donation;
			}
			set{
				m_Donation = value;
			}
		}

		public Reservation Reservation{
			get{
				return m_Reservation;
			}
			set{
				m_Reservation = value;
			}
		}

	}//end UTM Alumni

}//end namespace Business